version: "3.6"
services:
    php:
        build: .
        restart: always
        depends_on: 
            - mysql
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./log:/var/log/apache2
    mysql:
        image: mysql:8.0
        restart: always
        container_name: mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=sakila
            - MYSQL_USER=user
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=test
        volumes:
            - ./dump/1-create-db.sql:/docker-entrypoint-initdb.d/1.sql
            - ./dump/2-create-schema.sql:/docker-entrypoint-initdb.d/2.sql
            - ./dump/3-insert-data.sql:/docker-entrypoint-initdb.d/3.sql
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on: 
            - mysql
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql
            - PMA_ARBITRARY=1
volumes:
    persistent:
